### ISSUE TITLE
API_BASE_URL can't be overriden

### ISSUE THREAD

**Issue by gigaga** [Cezerin2/docker-cezerin2#3]
Hi,

Currently, my store UI is trying to get data from API by using http://localhost:3001 url.
I tried to change it by specifying the API_BASE_URL env variable in my docker-compose.yml to use the correct public address but it does not work.
Indeed, even after this change, my store UI still continues to use http://localhost:3001 url

Thanks,

**Comment by gigaga** [comment]
Indeed, after that, some requests still uses localhost:3001 :

- http://localhost:3001/assets/images/logo.png
- http://localhost:3001/assets/images/slide8.jpg
- http://localhost:3001/ajax/products

**Comment by LuBuss** [comment]
Can you please attach the docker-compose file or is this the default

**Comment by gigaga** [comment]
Hi @LuBuss ,

Of course!
Below my docker-compose.yml file. 192.168.25.2 is my host ip.

```
version: '3'

services:
  cezerin2:
    image: cezerin2/cezerin2
    ports:
      - 3001:80
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - DB_USER=
      - DB_PASS=
      - ASSETS_BASE_URL=http://192.168.25.2:3001
      - API_BASE_URL=http://192.168.25.2:3001/api/v1
      - STORE_URL=http://192.168.25.2:3000
      - ADMIN_BASE_URL=http://192.168.25.2:3002
    volumes:
      - ./content:/var/www/cezerin2/public/content
    depends_on:
      - db
    restart: always

  cezerin2-store:
    image: cezerin2/cezerin2-store
    environment:
      - API_BASE_URL=http://192.168.25.2:3001/api/v1
      - AJAX_BASE_URL=http://192.168.25.2:3001/ajax
    ports:
      - 3000:80
    depends_on:
      - cezerin2
    restart: always

  admin:
    image: cezerin2/cezerin2-admin
    ports:
      - 3002:80
    depends_on:
      - cezerin2
    restart: always

  db:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
```

**Comment by gigaga** [comment]
In fact, I have the same problem with the default docker-compose file.
If I try to access to store by using ip address, the front-end tries to get some data from localhost 😔

**Comment by LuBuss** [comment]
Can't have blank environment variables, remove `DB_USER` and `DB_PASS`.
That may fix your problem

**Comment by gigaga** [comment]
Thx @LuBuss for your response.
Unfortunately, I have the same issue :(

With the following docker-compose file : 
```
version: '3'

services:
 cezerin2:
   image: cezerin2/cezerin2
   ports:
     - 3001:80
   environment:
     - DB_HOST=db
     - DB_PORT=27017
     - DB_NAME=shop
   volumes:
     - ./content-on-host:/var/www/cezerin2/public/content
   depends_on:
     - db
   restart: always

 cezerin2-store:
   image: cezerin2/cezerin2-store
   environment:
     - API_BASE_URL=http://cezerin2/api/v1
     - AJAX_BASE_URL=http://cezerin2/ajax
   ports:
     - 3000:80
   depends_on:
     - cezerin2
   restart: always

 admin:
   image: cezerin2/cezerin2-admin
   ports:
     - 3002:80
   depends_on:
     - cezerin2
   restart: always

 db:
   image: mongo:3.6
   ports:
     - 27017:27017
   volumes:
     - ./db-on-host:/data/db
   restart: always
```

A browser the http://localhost:3000 works. A browser from another computer with http://<host_ip>:3000 doesn't work.
